myyrakle/rrdb

- src/lib/ast/dml/expressions/binary.rs
- src/lib/ast/dml/parts/join.rs
- src/lib/lexer/tokenizer.rs
- src/lib/parser/implements/dml/select.rs
- src/lib/parser/test/select.rs
- src/test.rs
> join parser

- src/lib/parser/implements/common.rs
- src/lib/parser/test/select.rs
> join 테스트 추가

- src/lib/executor/core.rs
- src/lib/executor/implements/ddl/create_database.rs
- src/lib/executor/mod.rs
- src/lib/executor/predule.rs
- src/lib/executor/result.rs
- src/lib/pgwire/connection/connection.rs
- src/lib/pgwire/connection/prepared_statement.rs
- src/lib/pgwire/engine/engine.rs
- src/lib/pgwire/engine/rrdb.rs
- src/lib/pgwire/protocol/message/backend/types/error_response.rs
- src/lib/server/channel.rs
- src/lib/server/core.rs
- src/lib/server/mod.rs
- src/lib/server/predule.rs
- src/lib/server/process_unit.rs
- src/lib/server/shared_state.rs
1. 프로토콜 코드 개선
2. executor 보완 및 반환타입 구성
3. executor 등과 커넥션루프 사이의 비동기 커뮤니케이션 구성
4. 기타등등
> pgwire 프로토콜 사용 커스텀 작업

- src/lib/executor/executor.rs
- src/lib/executor/implements/ddl/drop_database.rs
- src/lib/parser/implements/ddl/database.rs
drop database 기능 구현 완료
1. 파서 개선
2. executor 실제 동작 구현
> drop database 구현

- src/lib/errors/execute_error.rs
- src/lib/executor/executor.rs
- src/lib/executor/implements/ddl/alter_database.rs
- src/lib/executor/implements/ddl/mod.rs
- src/lib/lexer/tokenizer.rs
- src/lib/lexer/tokens.rs
- src/lib/parser/implements/ddl/database.rs
- src/lib/parser/implements/ddl/top_level.rs
- src/lib/parser/test/alter_database.rs
- src/lib/parser/test/mod.rs
1. 렉서 확장 (토큰 키워드 추가)
2. 파서 구현
3. 파서 테스트케이스 구현
4. executor 실행 구현
> alter database 기능 구현

- Cargo.toml
- README.md
- src/lib/ast/other/mod.rs
- src/lib/ast/other/use_database.rs
- src/lib/ast/types/statement.rs
- src/lib/executor/executor.rs
- src/lib/executor/implements/other/mod.rs
- src/lib/executor/implements/other/show_databases.rs
- src/lib/executor/implements/other/use_database.rs
- src/lib/lexer/tokenizer.rs
- src/lib/lexer/tokens.rs
- src/lib/logger/logger.rs
- src/lib/logger/mod.rs
- src/lib/logger/predule.rs
- src/lib/mod.rs
- src/lib/parser/implements/other/mod.rs
- src/lib/parser/implements/other/use.rs
- src/lib/parser/parser.rs
- src/lib/parser/test/other.rs
- src/lib/pgwire/connection/connection.rs
- src/lib/pgwire/protocol/connection_codec.rs
- src/lib/server/server.rs
- src/main.rs
1. 다중커넥션 처리 가능하게 개선
2. \c를 통한 DB 변경 기능 구현
3. use를 통한 DB 변경 기능 구현 (psql client 자체의 한계로 구현방식이 상이함. client 콘솔에서는 바뀌어보이지 않음.)
4. 로거 구현 및 일부 적용
5. 예외처리 보완
> use database 기능 관련

- Cargo.toml
- src/lib/ast/other/desc_table.rs
- src/lib/ast/other/mod.rs
- src/lib/ast/types/column.rs
- src/lib/ast/types/data_types.rs
- src/lib/ast/types/foreign_key.rs
- src/lib/ast/types/statement.rs
- src/lib/ast/types/table.rs
- src/lib/ast/types/unique_key.rs
- src/lib/executor/config/table.rs
- src/lib/executor/executor.rs
- src/lib/executor/implements/ddl/create_table.rs
- src/lib/executor/implements/other/desc_table.rs
- src/lib/executor/implements/other/mod.rs
- src/lib/logger/logger.rs
- src/lib/parser/implements/common.rs
- src/lib/parser/implements/ddl/table.rs
- src/lib/parser/implements/other/desc.rs
- src/lib/parser/implements/other/mod.rs
- src/lib/parser/parser.rs
- src/lib/parser/test/other.rs
- src/lib/pgwire/connection/connection.rs
- src/lib/server/client.rs
- src/lib/server/mod.rs
- src/lib/server/predule.rs
- src/lib/server/server.rs
- src/lib/server/shared_state.rs
1. create table 동작 구현
2. desc table 파서 및 동작 구현
3. 서버 로그 일부 추가, 정리.
4. client connection 정보 구조 추가
5. 자잘한 오류 수정
1. show tables 파서 및 동작 구현
2. drop table 동작 구현
3. alter table 동작 구현
> table 생성, 조회 구현

- src/lib/ast/other/mod.rs
- src/lib/ast/other/show_tables.rs
- src/lib/ast/types/statement.rs
- src/lib/executor/executor.rs
- src/lib/executor/implements/other/mod.rs
- src/lib/executor/implements/other/show_tables.rs
- src/lib/lexer/tokenizer.rs
- src/lib/lexer/tokens.rs
- src/lib/parser/implements/other/show.rs
- src/lib/parser/test/other.rs
> show tables 쿼리 구현

- src/lib/executor/executor.rs
- src/lib/executor/implements/ddl/drop_table.rs
- src/lib/pgwire/connection/connection.rs
- src/lib/pgwire/engine/rrdb.rs
- src/lib/server/server.rs
> drop table 구현

- README.md
- src/lib/ast/dml/insert.rs
- src/lib/ast/dml/parts/mod.rs
- src/lib/ast/dml/parts/select_item.rs
- src/lib/ast/dml/parts/target.rs
- src/lib/ast/dml/parts/where.rs
- src/lib/ast/dml/plan/mod.rs
- src/lib/ast/dml/plan/select/filter.rs
- src/lib/ast/dml/plan/select/from.rs
- src/lib/ast/dml/plan/select/scan.rs
- src/lib/ast/dml/plan/update/from.rs
- src/lib/ast/dml/plan/update/mod.rs
- src/lib/ast/dml/plan/update/update_plan.rs
- src/lib/ast/dml/update.rs
- src/lib/ast/types/expression.rs
- src/lib/executor/executor.rs
- src/lib/executor/implements/dml/insert.rs
- src/lib/executor/implements/dml/mod.rs
- src/lib/executor/implements/dml/select.rs
- src/lib/executor/implements/dml/update.rs
- src/lib/optimizer/optimizer.rs
- src/lib/parser/implements/dml/update.rs
1. update문 동작 구현
2. update 필터 구현
> update 쿼리 구현

- README.md
- src/lib/ast/dml/parts/order_by.rs
- src/lib/executor/config/row.rs
- src/lib/executor/implements/dml/select.rs
- src/lib/lexer/tokenizer.rs
- src/lib/lexer/tokens.rs
- src/lib/optimizer/optimizer.rs
- src/lib/parser/implements/dml/select.rs
- src/lib/parser/test/select.rs
1. order by optimize 구현
2. order by 동작 구현
3. nulls first|last 렉서, 파서 구현
4. nulls first|last 동작 구현
> select order by 구현

- Cargo.toml
- src/executor/config/global.rs
- src/executor/executor.rs
- src/executor/implements/ddl/create_database.rs
- src/executor/initializer.rs
- src/executor/mod.rs
- src/main.rs
resolved: #61
자잘한 리팩토링과 rrdb init 명령 사용시 linux daemon을 구성하는 기능 구현
> [#61] linux systemd 구성

- src/constants.rs
> [#93] MacOS에 대한 DEFAULT_CONFIG_BASEPATH 구성

- src/executor/initializer.rs
> [#102] launchd plist 정의 내 ProgramArguments 주입

- .github/workflows/pr_test.yml
- src/executor/initializer.rs
> [Feat] CI Actions에 대해 Max parallel jobs를 3으로 구성합니다.

- .github/workflows/review_stats.yml
resolves: #106
테스트하려고 디폴트 브랜치를 임시로 바꿈
> [#106] 리뷰 통계 워크플로 추가

- Cargo.toml
- README.md
- src/executor/initializer.rs
- src/lexer/test/select.rs
> [#120] v0.0.2 버전 배포

- src/utils/collection.rs
- src/utils/float.rs
- src/utils/macos.rs
> [#124] utils 테스트코드 작성

- src/ast/ddl/create_index.rs
- src/ast/ddl/create_table.rs
> [#128] ast::ddl 테스트코드 작성

- src/ast/dml/delete.rs
- src/ast/dml/expressions/between.rs
- src/ast/dml/expressions/binary.rs
- src/ast/dml/expressions/float.rs
- src/ast/dml/expressions/integer.rs
- src/ast/dml/expressions/not_between.rs
- src/ast/dml/expressions/operators.rs
- src/ast/dml/expressions/unary.rs
- src/ast/dml/plan/delete/delete_plan.rs
- src/ast/dml/plan/select/select_plan.rs
- src/ast/dml/plan/select/subquery.rs
- src/ast/dml/plan/update/update_plan.rs
- src/ast/dml/select.rs
- src/ast/dml/update.rs
> [#129] ast::dml 테스트코드 작성

- src/errors/execute_error.rs
- src/errors/into_error.rs
- src/errors/lexing_error.rs
- src/errors/mod.rs
- src/errors/parsing_error.rs
- src/errors/server_error.rs
- src/errors/type_error.rs
> [#132] error 모듈 테스트코드 작성

- src/logger/logger.rs
> [#133] Logger 테스트코드 작성

- src/ast/dml/delete.rs
- src/parser/parser.rs
- src/parser/test/alter_database.rs
- src/parser/test/alter_table.rs
- src/parser/test/create_database.rs
- src/parser/test/create_table.rs
- src/parser/test/delete.rs
- src/parser/test/drop_database.rs
- src/parser/test/drop_table.rs
- src/parser/test/expressions.rs
- src/parser/test/insert.rs
- src/parser/test/other.rs
- src/parser/test/select.rs
- src/parser/test/tcl.rs
- src/parser/test/update.rs
- src/pgwire/connection/connection.rs
resolves: #137
간단하게 해당 PR이 어떤 내용인지 작성합니다. 이슈를 통해서 충분히 설명이 가능 하다고 생각하면 resolves만 작성하시면 됩
니다.
> [#137] DeleteQuery 리팩토링, 테스트코드 작성

- src/ast/dml/update.rs
- src/parser/test/update.rs
> [#144] handle_update_query 테스트코드 작성 

- src/parser/test/other.rs
> [#139] parser::other 테스트코드 추가 

- src/parser/implements/ddl/database.rs
- src/parser/implements/ddl/table.rs
- src/parser/test/alter_database.rs
- src/parser/test/create_database.rs
- src/parser/test/ddl.rs
- src/parser/test/drop_database.rs
- src/parser/test/mod.rs
> [#110] parser:ddl 테스트코드 작성
